<?php


$gltr_ua = array(
"Mozilla/1.1 (compatible; MSPIE 2.0; Windows CE)",
"Mozilla/1.10 [en] (Compatible; RISC OS 3.70; Oregano 1.10)",
"Mozilla/1.22 (compatible; MSIE 2.0d; Windows NT)",
"Mozilla/1.22 (compatible; MSIE 5.01; PalmOS 3.0)",
"Mozilla/2.0 (compatible; AOL 3.0; Mac_PowerPC)",
"Mozilla/2.0 (Compatible; AOL-IWENG 3.0; Win16)",
"Mozilla/2.0 (compatible; MS FrontPage x.0)",
"Mozilla/2.0 (compatible; MSIE 2.1; Mac_PowerPC)",
"Mozilla/2.0 (compatible; MSIE 3.02; Update a; AK; Windows NT)",
"Mozilla/2.0 (compatible; MSIE 3.02; Update a; AOL 3.0; Windows 95)",
"Mozilla/2.0 (compatible; MSIE 3.0; AK; Windows 95)",
"Mozilla/2.0 (compatible; MSIE 3.0; Windows 3.1)",
"Mozilla/2.0 (compatible; MSIE 3.0B; Win32)",
"Mozilla/2.01 (Win16; I)",
"Mozilla/2.02Gold (Win95; I)",
"Mozilla/3.0 (compatible; AvantGo 3.2)",
"Mozilla/3.0 (compatible; NetPositive/2.2)",
"Mozilla/3.0 (compatible; Opera/3.0; Windows 3.1)",
"Mozilla/3.0 (compatible; Opera/3.0; Windows 95/NT4)",
"Mozilla/3.0 (Planetweb/2.100 JS SSL US; Dreamcast US)",
"Mozilla/3.0 (Win16; I)",
"Mozilla/3.0 (Win95; I)",
"Mozilla/3.0 (WinNT; I)",
"Mozilla/3.0 (WorldGate Gazelle 3.5.1 build 11; FreeBSD2.2.8-STABLE)",
"Mozilla/3.0 (X11; I; OSF1 V4.0 alpha)",
"Mozilla/3.0 NAVIO_AOLTV (11; 13; Philips; PH200; 1; R2.0C36_AOL.0110OPTIK; R2.0.0139d_OPTIK)",
"Mozilla/3.0 WebTV/1.2 (compatible; MSIE 2.0)",
"Mozilla/3.01 (compatible; AmigaVoyager/2.95; AmigaOS/MC680x0)",
"Mozilla/3.01 (compatible; Netbox/3.5 R92; Linux 2.2)",
"Mozilla/3.01-C-MACOS8 (Macintosh; I; PPC)",
"Mozilla/3.01Gold (X11; I; Linux 2.0.32 i486)",
"Mozilla/3.01Gold (X11; I; SunOS 5.5.1 sun4m)",
"Mozilla/3.01SGoldC-SGI (X11; I; IRIX 6.3 IP32)",
"Mozilla/3.04 (compatible; ANTFresco/2.13; RISC OS 4.02)",
"Mozilla/3.04 (compatible; NCBrowser/2.35; ANTFresco/2.17; RISC OS-NC 5.13 Laz1UK1309)",
"Mozilla/3.04 (compatible;QNX Voyager 2.03B ;Photon)",
"Mozilla/3.x (I-Opener 1.1; Netpliance)",
"Mozilla/4.0 (compatible; ibisBrowser)",
"Mozilla/4.0 (compatible; Lotus-Notes/5.0; Windows-NT)",
"Mozilla/4.0 (compatible; MSIE 4.01; AOL 4.0; Windows 98)",
"Mozilla/4.0 (compatible; MSIE 4.01; Mac_PowerPC)",
"Mozilla/4.0 (compatible; MSIE 4.01; Windows 95)",
"Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; MSN Companion 2.0; 800x600; Compaq)",
"Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; PPS; 240x320)",
"Mozilla/4.0 (compatible; MSIE 4.01; Windows NT Windows CE)",
"Mozilla/4.0 (compatible; MSIE 4.01; Windows NT)",
"Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; NetCaptor 6.5.0RC1)",
"Mozilla/4.0 (compatible; MSIE 5.0; AOL 5.0; Windows 95; DigExt; Gateway2000; sureseeker.com)",
"Mozilla/4.0 (compatible; MSIE 5.0; Mac_PowerPC; AtHome021)",
"Mozilla/4.0 (compatible; MSIE 5.0; Windows ME)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; Crazy Browser 1.x.x)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; KITV4.7 Wanadoo)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; SAFEXPLORER TL)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; SYMPA; Katiesoft 7; SimulBrowse 3.0)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; Win 9x 4.90; BTinternet V8.1)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0; .NET CLR 1.0.3705)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0; AIRF)",
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0; N_o_k_i_a)",
"Mozilla/4.0 (compatible; MSIE 6.0; AOL 9.0; Windows NT 5.1; SV1; HbTools 4.7.2)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Net M@nager V3.02 - www.vinn.com.au)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.1.4322; Lunascape 2.1.3)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Deepnet Explorer)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Hotbar 3.0)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; iOpus-I-M)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman3.0)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; MathPlayer2.0)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Maxthon)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; PeoplePal 3.0; MSIECrawler)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Q312461; IOpener Release 1.1.04)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SIMBAR Enabled; InfoPath.1)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; StumbleUpon.com 1.760; .NET CLR 1.1.4322)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Embedded Web Browser from: http://bsalsa.com/; MSIECrawler)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; DX-Browser 5.0.0.0)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; FunWebProducts; ezPeer+ v1.0 Beta (0.4.1.98)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; IBP; .NET CLR 1.1.4322)",
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; MRA 4.3 (build 01218)",
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; bgft)",
"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)",
"Mozilla/4.0 (compatible; Opera/3.0; Windows 4.10)",
"Mozilla/4.0 (compatible; RSS Popper)",
"Mozilla/4.0 (compatible; SiteKiosk 4.0; MSIE 5.0; Windows 98; SiteCoach 1.0)",
"Mozilla/4.0 (MobilePhone PM-8200/US/1.0)",
"Mozilla/4.0 WebTV/2.6 (compatible; MSIE 4.0)",
"Mozilla/4.02 [en] (X11; I; SunOS 5.6 sun4u)",
"Mozilla/4.04 [en] (X11; I; HP-UX B.10.20 9000/712)",
"Mozilla/4.04 [en] (X11; I; IRIX 5.3 IP22)",
"Mozilla/4.05 (Macintosh; I; 68K Nav)",
"Mozilla/4.05 (Macintosh; I; PPC Nav)",
"Mozilla/4.05 [en] (X11; I; SunOS 4.1.4 sun4m)",
"Mozilla/4.08 [en] (WinNT; U)",
"Mozilla/4.5 (compatible; iCab 2.5.3; Macintosh; I; PPC)",
"Mozilla/4.5 (compatible; OmniWeb/4.0.5; Mac_PowerPC)",
"Mozilla/4.5 (compatible; OmniWeb/4.1-beta-1; Mac_PowerPC)",
"Mozilla/4.5 [en]C-CCK-MCD {RuralNet} (Win98; I)",
"Mozilla/4.5b1 [en] (X11; I; Linux 2.0.35 i586)",
"Mozilla/4.61 [de] (OS/2; I)",
"Mozilla/4.61 [en] (X11; U; )",
"Mozilla/4.7 (compatible; OffByOne; Windows 98)",
"Mozilla/4.72C-CCK-MCD Caldera Systems OpenLinux [en] (X11; U; Linux 2.2.14 i686)",
"Mozilla/4.75C-ja [ja] (X11; U; OSF1 V5.1 alpha)",
"Mozilla/4.76 (Windows 98; U)",
"Mozilla/4.76 [en] (X11; U; FreeBSD 4.4-STABLE i386)",
"Mozilla/4.76 [en] (X11; U; SunOS 5.7 sun4u)",
"Mozilla/4.77C-SGI [en] (X11; U; IRIX 6.5 IP32)",
"Mozilla/5.0 (compatible)",
"Mozilla/5.0 (compatible; Konqueror/2.0.1; X11)",
"Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)",
"Mozilla/5.0 (compatible; Konqueror/2.2.2)",
"Mozilla/5.0 (compatible; Konqueror/2.2.2; Linux 2.4.14-xfs; X11; i686)",
"Mozilla/5.0 (compatible; Phonifier; +http://www.phonifier.com)",
"Mozilla/5.0 (compatible; SnapPreviewBot; en-US; rv:1.8.0.9)",
"Mozilla/5.0 (compatible;FindITAnswersbot/1.0;+http://search.it-influentials.com/bot.htm)",
"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4; en-US; rv:1.9b5)",
"Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.0.1)",
"Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.0.1)",
"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US)",
"Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us)",
"Mozilla/5.0 (Macintosh; U; PPC; en-US; rv:0.9.2)",
"Mozilla/5.0 (Sage)",
"Mozilla/5.0 (SunOS 5.8 sun4u; U)",
"Mozilla/5.0 (Windows; U; Win98; en-US; rv:0.9.2)",
"Mozilla/5.0 (Windows; U; Win98; en-US; rv:x.xx)",
"Mozilla/5.0 (Windows; U; Win9x; en; Stable)",
"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.5)",
"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:x.x.x)",
"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:x.xx)",
"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:x.xxx)",
"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9b5)",
"Mozilla/5.0 (Windows; U;XMPP Tiscali Communicator v.10.0.1; Windows NT 5.1; it; rv:1.8.1.3)",
"Mozilla/5.0 (X11; Linux i686; U;rv: 1.7.13)",
"Mozilla/5.0 (X11; U; Linux 2.4.2-2 i586; en-US; m18)",
"Mozilla/5.0 (X11; U; Linux i686; de-AT; rv:1.8.0.2)",
"Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.7.6)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; Nautilus/1.0Final)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:0.9.3)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2b)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.6)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.0.7)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1)",
"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.1)",
"Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9a8)",
"Mozilla/5.0 Galeon/1.0.2 (X11; Linux i686; U;)"
);

function gltr_sitemap_plugin_detected(){
	if (function_exists('get_plugins')){
		$all_plugins = get_plugins();
		foreach( (array)$all_plugins as $plugin_file => $plugin_data) {
			if ($plugin_file == 'google-sitemap-generator/sitemap.php') return true;
		}
		return false;
	} else
		return true;
}

function gltr_create_file($datafile){
	$success = true;
	if (!file_exists($datafile)){
      if (($handle = @fopen($datafile, "wb")) === false) return false;
	    if ((@fwrite($handle, '')) === false) return false;
      @fclose($handle);
	} 
	return true;
}

if (!function_exists('file_get_contents')) {
	function file_get_contents($filename, $incpath = false, $resource_context = null) {
		if (false === $handle = fopen($filename, 'rb', $incpath)) {
			return false;
		}
		if ($fsize = @filesize($filename)) {
			$buf = fread($handle, $fsize);
		} else {
			$buf = '';
			while (!feof($handle)) {
				$buf .= fread($handle, 8192);
			}
		}
		fclose($handle);
		return $buf;
	}	
}
if(!class_exists("gltr_translation_engine")) {
	class gltr_translation_status {
		
		var $_status;
		var $_last_connection_time;
		
		function gltr_translation_status() {
			$exists = get_option("gltr_translation_status");
			if($exists === false){ 
				add_option("gltr_translation_status","");
			}
			$this->save();
		}
		
		function save() {
			update_option("gltr_translation_status",$this);		
		}		

		function load() {
			$status = @get_option("gltr_translation_status");
			if(is_a($status,"gltr_translation_status")) return $status;
			else return null;	
		}
			
    function save_status($status){
    	$this->_status = $status;
    	$this->save();
    }

    function get_status(){
    	return $this->_status;
    }
		
    function save_last_connection_time($last_connection_time){
    	$this->_last_connection_time = $last_connection_time;
    	$this->save();
    }

    function get_last_connection_time(){
    	return $this->_last_connection_time;
    }
		

	}

}


if(!class_exists("gltr_translation_engine")) {
	class gltr_translation_engine {
		var $_name;

		var	$_base_url;

		var $_links_pattern;

		var $_links_replacement;

		var $_languages_matrix;

		var $_available_languages;

		function gltr_translation_engine(
			$name,
			$base_url,
			$links_pattern,
			$links_replacement,
			$languages_matrix,
			$available_languages) {
	      $this->set_name($name);
        $this->set_base_url($base_url);
        $this->set_links_pattern($links_pattern);
        $this->set_links_replacement($links_replacement);
        $this->set_languages_matrix($languages_matrix);
        $this->set_available_languages($available_languages);
		}

    function set_name($name){
    	$this->_name = (string)$name;
    }

		function set_base_url($base_url){
    	$this->_base_url = (string)$base_url;
    }

		function set_links_pattern($links_pattern){
    	$this->_links_pattern = (array)$links_pattern;
    }

		function set_links_replacement($links_replacement){
    	$this->_links_replacement = (string)$links_replacement;
    }

		function set_languages_matrix($languages_matrix){
    	$this->_languages_matrix = (array)$languages_matrix;
    }

		function set_available_languages($available_languages){
    	$this->_available_languages = (array)$available_languages;
    }

    function get_name(){
    	return $this->_name;
    }

		function get_base_url(){
    	return $this->_base_url;
    }

		function get_links_pattern(){
    	return $this->_links_pattern;
    }

		function get_links_replacement(){
    	return $this->_links_replacement;
    }

		function get_languages_matrix(){
    	return $this->_languages_matrix;
    }

		function get_available_languages(){
    	return $this->_available_languages;
    }

    function decode_lang_code($res)
    {
      if ($this->_name == 'promt') {
        if ($res == 'es') $res = 's';
        else if ($res == 'de') $res = 'g';
        else $res = substr($res, 0, 1);
      } else if ($this->_name == 'freetransl') {
        $map = array(
      	  'en'    => 'English',
      	  'es'    => 'Spanish',
      	  'fr'    => 'French',
      	  'de'    => 'German',
      	  'it'    => 'Italian',
      	  'nl'    => 'Dutch',
      	  'pt'    => 'Portuguese',
      	  'no'    => 'Norwegian');
     	  $res = $map[$res];
      }
      return $res;
    }
    
    function build_clean_link($matches){
    	$res = "href=";
    	foreach($this->_match_id as $key=>$val){
    		
    	}
			return urldecode();
		}

	}
}

$googleEngine = new gltr_translation_engine(
	'google',
	'http://translate.google.com/translate_n?hl=en&ie=UTF-8&oe=UTF-8&langpair=${SRCLANG}|${DESTLANG}&u=${URL}&prev=/language_tools',
	array(
		"/href=[']{1}[^']*u=(.*?)&amp;([^'|#]*)([#]{0,1}[^']*)[']{1}/",
		"/href=[\"]{1}[^\"]*u=(.*?)&amp;([^\"|#]*)([#]{0,1}[^\"]*)[\"]{1}/"
		//"/href=[']{1}[^']*u=(.*?)&amp;prev=\/language_tools[^']*([#]{0,1}[^\"]*)[']{1}/",
		//"/href=[\"]{1}[^\"]*u=(.*?)&amp;prev=\/language_tools[^\"]*([#]{0,1}[^\"]*)[\"]{1}/"
	),
	"href=\"\\1\" ",
	array(
  'it'    => array( 'it'=>'Italiano',
                    'ar'=>'Arabo',
                    'bg'=>'Bulgaro',
                    'ca'=>'Catalano',
                    'zh-CN'=>'Cinese',
                    'hr'=>'Croato',
                    'cs'=>'Ceco',
                    'da'=>'Danese',
                    'nl'=>'Olandese',
                    'en'=>'Inglese',
                    'tl'=>'Filippino',
                    'fi'=>'Finlandese',
                    'fr'=>'Francese',
                    'de'=>'Tedesco',
                    'el'=>'Greco',
										'iw'=>'Ebraico',
                    'hi'=>'Hindi',
										'id'=>'Indonesiano',
                    'ja'=>'Giapponese',
                    'ko'=>'Coreano',
										'lv'=>'Lettone',
										'lt'=>'Lituano',
    								'no'=>'Norvegese',
                    'pl'=>'Polacco',
                    'pt'=>'Portoghese',
                    'ro'=>'Rumeno',
                    'ru'=>'Russo',
										'sr'=>'Serbo',
										'sk'=>'Slovacco',
										'sl'=>'Sloveno',
                    'es'=>'Spagnolo',
                    'sv'=>'Svedese',
                    'uk'=>'Ucraino',
                    'vi'=>'Vietnamita'
                    ),
  'ko'    => array( 'ko'    => 'Korean',
									  'it'    => 'Italian',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=> 'Bulgarian',
								    'cs'		=> 'Czech',
								    'hr'		=> 'Croat',
								    'da'		=> 'Danish',
								    'fi'		=> 'Finnish',
								    'hi'		=> 'Hindi',
								    'pl'		=> 'Polish',
								    'ro'		=> 'Rumanian',
								    'sv'		=> 'Swedish',
								    'el'		=> 'Greek',
    								'no'		=> 'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'zh-CN' => array( 'zh-CN' => 'Chinese (Simplified)',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=> 'Bulgarian',
								    'cs'		=> 'Czech',
								    'hr'		=> 'Croat',
								    'da'		=> 'Danish',
								    'fi'		=> 'Finnish',
								    'hi'		=> 'Hindi',
								    'pl'		=> 'Polish',
								    'ro'		=> 'Rumanian',
								    'sv'		=> 'Swedish',
								    'el'		=> 'Greek',
    								'no'		=> 'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'pt'    => array( 'pt'    => 'Portuguese',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'en'    => array( 'en'    => 'English',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'de'    => array( 'de'    => 'German',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
									),
  'fr'    => array( 'fr'    => 'French',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'es'    => array( 'es'    => 'Spanish',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'ja'    => array( 'ja'    => 'Japanese',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'ar'    => array( 'ar'    => 'Arabic',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'ru'    => array( 'ru'		=> 'Russian',
									  'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'el'    => array( 'el'		=>'Greek',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'nl'    => array( 'nl'		=> 'Dutch',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'bg'    => array( 'bg'		=>'Bulgarian',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'cs'    => array( 'cs'		=>'Czech',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'hr'    => array( 'hr'		=>'Croat',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'da'    => array( 'da'		=>'Danish',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'fi'    => array( 'fi'		=>'Finnish',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'hi'    => array( 'hi'		=>'Hindi',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'pl'    => array( 'pl'		=>'Polish',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'ro'		=>'Rumanian',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'ro'    => array( 'ro'		=>'Rumanian',
								    'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'sv'		=>'Swedish',
								    'el'		=>'Greek',
    								'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'sv'    => array( 'sv'		=>'Swedish',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),

  'ca'    => array( 'ca'    => 'Catalan',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'tl'    => array( 'tl'    => 'Filipino',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'iw'    => array( 'iw'		=> 'Hebrew',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',								    
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'id'    => array( 'id'		=> 'Indonesian',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',								    
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'lv'    => array( 'lv'		=> 'Latvian',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',								    
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'lt'    => array( 'lt'		=> 'Lithuanian',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',								    
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'sr'    => array( 'sr'		=> 'Serbian',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',								    
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'sk'    => array( 'sk'		=> 'Slovak',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',								    
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'sl'    => array( 'sl'		=> 'Slovenian',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',								    
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'uk'    => array( 'uk'		=> 'Ukrainian',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian',
								    'vi'		=> 'Vietnamese'
                    ),
  'vi'    => array( 'vi'		=> 'Vietnamese',
    								'it'    => 'Italian',
									  'ko'    => 'Korean',
									  'zh-CN' => 'Chinese (Simplified)',
									  'pt'    => 'Portuguese',
									  'en'    => 'English',
									  'de'    => 'German',
									  'fr'    => 'French',
									  'es'    => 'Spanish',
									  'ja'    => 'Japanese',
									  'ar'    => 'Arabic',
									  'ru'		=> 'Russian',
									  'el'    => 'Greek',
									  'nl'		=> 'Dutch',
								    'bg'		=>'Bulgarian',
								    'cs'		=>'Czech',
								    'hr'		=>'Croat',
								    'da'		=>'Danish',
								    'fi'		=>'Finnish',
								    'hi'		=>'Hindi',
								    'pl'		=>'Polish',
								    'ro'		=>'Rumanian',
								    'no'		=>'Norwegian',
								    'sv'		=>'Swedish',
								    'ca'    => 'Catalan',
								    'tl'    => 'Filipino',
								    'iw'		=> 'Hebrew',
								    'id'		=> 'Indonesian',
								    'lv'		=> 'Latvian',
								    'lt'		=> 'Lithuanian',
								    'sr'		=> 'Serbian',
								    'sk'		=> 'Slovak',
								    'sl'		=> 'Slovenian',
								    'uk'		=> 'Ukrainian'								    
                    ),
  ),

	array(
	  'it'    => 'Italian',
	  'ko'    => 'Korean',
	  'zh-CN' => 'Chinese (Simplified)',
	  'pt'    => 'Portuguese',
	  'en'    => 'English',
	  'de'    => 'German',
	  'fr'    => 'French',
	  'es'    => 'Spanish',
	  'ja'    => 'Japanese',
	  'ar'    => 'Arabic',
	  'ru'		=> 'Russian',
	  'el'    => 'Greek',
	  'nl'		=> 'Dutch',
    'bg'		=> 'Bulgarian',
    'cs'		=> 'Czech',
    'hr'		=> 'Croatian',
    'da'		=> 'Danish',
    'fi'		=> 'Finnish',
    'hi'		=> 'Hindi',
    'pl'		=> 'Polish',
    'ro'		=> 'Romanian',
    'sv'		=> 'Swedish',
    'no'		=> 'Norwegian',
    'ca'    => 'Catalan',
    'tl'    => 'Filipino',
    'iw'		=> 'Hebrew',
    'id'		=> 'Indonesian',
    'lv'		=> 'Latvian',
    'lt'		=> 'Lithuanian',
    'sr'		=> 'Serbian',
    'sk'		=> 'Slovak',
    'sl'		=> 'Slovenian',
    'uk'		=> 'Ukrainian',
    'vi'		=> 'Vietnamese'
	  )

	);


$babelfishEngine = new gltr_translation_engine(
	'babelfish',
	'http://babelfish.altavista.com/babelfish/trurl_pagecontent?lp=${SRCLANG}_${DESTLANG}&url=${URL}',
	//array("/<a(.*?)href=\"(.*?)url=(.*?)\"([\s|>]{1})/i"),
	array(
		"/href=[']{1}[^']*url=(.*?)[']{1}/",
		"/href=[\"]{1}[^\"]*url=(.*?)[\"]{1}/"
	),		
	"<a href=\"\\1\" ",
	array(
  'it'    => array( 'it'=>'Italiano',
                    'en'=>'Inglese',
                    'fr'=>'Francese'),
  'ko'    => array( 'ko'=>'Korean',
                    'en'=>'English'),
  'zh' 		=> array( 'zh'=>'Chinese (Simplified)',
                    'en'=>'English'),
  'zt' 		=> array( 'zt'=>'Chinese (Traditional)',
                    'en'=>'English'),
  'pt'    => array( 'pt'=>'Portugues',
                    'en'=>'Ingles',
                    'fr'=>'Francais'),//to be verified
  'en'    => array( 'en'=>'English',
                    'zh'=>'Chinese (Simplified)',
                    'zt'=>'Chinese (Traditional)',
                    'nl'=>'Dutch',
                    'fr'=>'French',
                    'de'=>'German',
                    'el'=>'Greek',
                    'it'=>'Italian',
                    'ja'=>'Japanese',
                    'ko'=>'Korean',
                    'pt'=>'Portuguese',
                    'ru'=>'Russian',
                    'es'=>'Spanish'),
  'nl'    => array( 'nl'=>'Dutch',
  									'en'=>'English',
  									'fr'=>'French'),
  'de'    => array( 'de'=>'Deutsch',
                    'en'=>'Englisch',
                    'fr'=>'Franzosisch'),
  'fr'    => array( 'fr'=>'Francais',
                    'en'=>'Anglais',
                    'de'=>'Allemand',
                    'el'=>'Grec',
                    'it'=>'Italien',
                    'pt'=>'Portugais',
                    'es'=>'Espagnol',
                    'nl'=>'Hollandais'),
  'el'    => array( 'el'=>'Greek',
  									'en'=>'English',
  									'fr'=>'French'),
  'es'    => array( 'es'=>'Espanol',
                    'en'=>'Ingles'),
  'ja'    => array( 'ja'=>'Japanese',
                    'en'=>'English'),
  'ru'    => array( 'ru'=>'Russian',
                    'en'=>'English')
  ),

	array(
	  'it'    => 'Italian',
	  'ko'    => 'Korean',
	  'zh' 		=> 'Chinese (Simplified)',
	  'zt' 		=> 'Chinese (Traditional)',
	  'pt'    => 'Portuguese',
	  'en'    => 'English',
	  'el'    => 'Greek',
	  'nl'    => 'Dutch',
	  'de'    => 'German',
	  'fr'    => 'French',
	  'es'    => 'Spanish',
	  'ja'    => 'Japanese',
	  'ru'		=> 'Russian'
	  )
	);

$promtEngine = new gltr_translation_engine(
  'promt',
  'http://beta.translate.ru/url/translation.aspx?autotranslate=on&sourceURL=${URL}&direction=${SRCLANG}${DESTLANG}',
  //old version 'http://beta.online-translator.com/url/tran_url.asp?prmtlang=en&autotranslate=on&url=${URL}&direction=${SRCLANG}${DESTLANG}',
  //old version 'http://www.online-translator.com/url/tran_url.asp?url=${URL}&direction=${SRCLANG}${DESTLANG}&cp1=UTF-8&cp2=UTF-8&autotranslate=on',
  //array("/href=\"(.*?)url=(.*?)\"([\s|>]{1})/i"),
	array(
		"/href=[']{1}[^']*sourceURL=([^'|#]*)([#]{0,1}[^']*)[']{1}/",
		"/href=[\"]{1}[^\"]*sourceURL=([^\"|#]*)([#]{0,1}[^\"]*)[\"]{1}/"
	),  
	"href=\"\\1\" ",
  array(
  'it'    => array( 'it'=>'Italiano',
                    'en'=>'Inglese',
                    'ru'=>'Russo'),
  'pt'    => array( 'pt'=>'Portugues',
                    'en'=>'Ingles'),//to be verified
  'en'    => array( 'en'=>'English',
                    'fr'=>'French',
                    'de'=>'German',
                    'it'=>'Italian',
                    'pt'=>'Portuguese',
                    'ru'=>'Russian',
                    'es'=>'Spanish'),
  'de'    => array( 'de'=>'Deutsch',
                    'en'=>'Englisch',
                    'fr'=>'Franzosisch',
                    'es'=>'Spanish',
                    'ru'=>'Russian'
                    ),
  'fr'    => array( 'fr'=>'Francais',
                    'en'=>'Anglais',
                    'de'=>'Allemand',
                    'ru'=>'Russian', //
                    'es'=>'Espagnol'),
  'es'    => array( 'es'=>'Espanol',
                    'en'=>'Ingles',
                    'ru'=>'Russian',
                    'de'=>'German',
                    'fr'=>'French'
                    ),
  'ru'    => array( 'ru'=>'Russian',
                    'en'=>'English',
                    'fr'=>'French',
                    'de'=>'German',
                    'es'=>'Spanish'
                    )
  ),



  array(
    'it'    => 'Italian',
    'pt'    => 'Portuguese',
    'en'    => 'English',
    'de'    => 'German',
    'fr'    => 'French',
    'es'    => 'Spanish',
    'ru'    => 'Russian'
    )
  );

$freetranslationEngine = new gltr_translation_engine(
  'freetransl',
  'http://fets5.freetranslation.com/?sequence=core&language=${SRCLANG}/${DESTLANG}&url=${URL}',
  array("/href=\"([^\"]*)\"/i"),
  "href=\"\\1\"", 
  array(
  'it'    => array( 'it'=>'Italiano',
                    'en'=>'Inglese'),
  'pt'    => array( 'pt'=>'Portugues',
                    'en'=>'Ingles'),//to be verified
  'en'    => array( 'en'=>'English',
                    'es'=>'Spanish',
                    'fr'=>'French',
                    'de'=>'German',
                    'it'=>'Italian',
                    'nl'=>'Dutch',
                    'pt'=>'Portuguese',
                    'no'=> 'Norwegian'
                    ),
  'de'    => array( 'de'=>'Deutsch',
                    'en'=>'Englisch'
                    ),
  'fr'    => array( 'fr'=>'Francais',
                    'en'=>'Anglais'
                    ),
  'es'    => array( 'es'=>'Espanol',
                    'en'=>'Ingles',
                    ),
  'nl'    => array( 'nl'=>'Dutch',
                    'en'=>'English'
                    )
  ),

  array(
    'it'    => 'Italian',
    'pt'    => 'Portuguese',
    'en'    => 'English',
    'de'    => 'German',
    'fr'    => 'French',
    'es'    => 'Spanish',
    'no'    => 'Norwegian',
    'nl'    => 'Dutch',
    )
  );

$well_known_extensions =  array('swf','gif','jpg','jpeg','bmp','gz','zip','rar','tar','png','xls','doc','ppt','tiff','avi','mpeg','mp3','mov','mp4');

$gltr_available_engines = array();
$gltr_available_engines['google'] = $googleEngine;
$gltr_available_engines['promt'] = $promtEngine;
$gltr_available_engines['babelfish'] = $babelfishEngine;
$gltr_available_engines['freetransl'] = $freetranslationEngine;


/*Lets add some default options if they don't exist*/
add_option('gltr_base_lang', 'en');
add_option('gltr_col_num', '0');
add_option('gltr_html_bar_tag', 'TABLE');
add_option('gltr_my_translation_engine', 'google');
add_option('gltr_preferred_languages', array());
add_option('gltr_ban_prevention', true);
add_option('gltr_enable_debug', false);
add_option('gltr_conn_interval',300);
add_option('gltr_sitemap_integration',false);
add_option("gltr_last_connection_time",0);
add_option("gltr_translation_status","unknown");
add_option("gltr_cache_expire_time",30);
if (function_exists('gzcompress')){
	add_option("gltr_compress_cache",true);
} else {
	add_option("gltr_compress_cache",false);
}
$gltr_VERSION='1.0.7';
?>